package modelo

/**
 * Constantes para utilizar a lo largo de todo el modelo.
 */
const (
	CONN_TIPO = "tcp"

	CMD_PREFIX = ""

	CMD_AYUDA           = CMD_PREFIX + "HELP"
	CMD_CREAR           = CMD_PREFIX + "CREATEROOM"
	CMD_ENTRAR          = CMD_PREFIX + "JOINROOM"
	CMD_ESTADO          = CMD_PREFIX + "STATUS"
	CMD_HISTORIAL       = CMD_PREFIX + "HISTORY"
	CMD_INVITAR         = CMD_PREFIX + "INVITE"
	CMD_MENSAJE_DIRECTO = CMD_PREFIX + "MESSAGE"
	CMD_MENSAJE_PUBLICO = CMD_PREFIX + "PUBLICMESSAGE"
	CMD_MENSAJE_SALA    = CMD_PREFIX + "ROOMESSAGE"
	CMD_NOMBRE          = CMD_PREFIX + "IDENTIFY"
	CMD_SALAS           = CMD_PREFIX + "ROOMS"
	CMD_SALIR           = CMD_PREFIX + "LEAVEROOM"
	CMD_STATUS          = CMD_PREFIX + "STATUS"
	CMD_TERMINAR        = CMD_PREFIX + "DISCONNECT"
	CMD_USUARIOS        = CMD_PREFIX + "USERS"

	STS_ACTIVE = "ACTIVE"
	STS_AWAY   = "AWAY"
	STS_BUSY   = "BUSY"

	CLIENTE_NOMBRE  = ""
	SERVIDOR_NOMBRE = "Servidor"

	ERROR_PREFIJO           = "..."
	ERROR_NOMBRE_USUARIO    = ERROR_PREFIJO + "USERNAME NOT AVAILABLE\n"
	ERROR_NOMBRE_SALA       = ERROR_PREFIJO + "ROOM NAME ALREADY IN USE\n"
	ERROR_ENTRAR_NO_EXISTE  = ERROR_PREFIJO + "ROOM NOT EXISTS\n"
	ERROR_ENTRAR_INVITACION = ERROR_PREFIJO + "YOU ARE NOT INVITED TO ROOM %s\n"
	ERROR_ENTRAR_PERTENECE  = ERROR_PREFIJO + "ALREADY EXISTS IN ROOM\n"
    ERROR_INVITACION        = ERROR_PREFIJO + "YOU ARE NOT THE OWNER OF THE ROOM\n"
	ERROR_SALA              = ERROR_PREFIJO + "YOU ARE NOT PART OF THE ROOM\n"

	MENSAJE_ENVIADO = "...MESSAGE SENT\n"

	EVENTO_PREFIJO             = "..."
	EVENTO_ENTRA_SALA          = EVENTO_PREFIJO + "\"%s\" SE UNIÓ A LA SALA\n"
	EVENTO_SALA_NOMBRE         = EVENTO_PREFIJO + "\"%s\" CAMBIÓ SU NOMBRE A \"%s\"\n"
	EVENTO_PERSONAL_CREAR      = EVENTO_PREFIJO + "ROOM CREATED\n"
	EVENTO_ESTADO              = EVENTO_PREFIJO + "%s %s\n"
	EVENTO_PERSONAL_NOMBRE     = EVENTO_PREFIJO + "SUCCESSFUL IDENTIFICATION\n"
	EVENTO_PERSONAL_ESTADO     = EVENTO_PREFIJO + "CAMBIASTE TU ESTADO A \"%s\"\n"

	MSJ_DESCONECTA = "\nDesconectado del servidor.\n"
)
