package modelo

const (
	CONN_TIPO = "tcp"

	CMD_PREFIX = ""

	CMD_AYUDA           = CMD_PREFIX + "HELP"
	CMD_CREAR           = CMD_PREFIX + "CREATEROOM"
	CMD_ENTRAR          = CMD_PREFIX + "JOINROOM"
	CMD_ESTADO          = CMD_PREFIX + "STATUS"
	CMD_HISTORIAL       = CMD_PREFIX + "HISTORY"
	CMD_INVITAR         = CMD_PREFIX + "INVITE"
	CMD_MENSAJE_DIRECTO = CMD_PREFIX + "MESSAGE"
	CMD_MENSAJE_PUBLICO = CMD_PREFIX + "PUBLICMESSAGE"
	CMD_MENSAJE_SALA    = CMD_PREFIX + "ROOMESSAGE"
	CMD_NOMBRE          = CMD_PREFIX + "IDENTIFY"
	CMD_SALAS           = CMD_PREFIX + "ROOMS"
	CMD_SALIR           = CMD_PREFIX + "LEAVEROOM"
	CMD_STATUS          = CMD_PREFIX + "STATUS"
	CMD_TERMINAR        = CMD_PREFIX + "DISCONNECT"
	CMD_USUARIOS        = CMD_PREFIX + "USERS"

	STS_ACTIVE = "ACTIVE"
	STS_AWAY   = "AWAY"
	STS_BUSY   = "BUSY"

	CLIENTE_NOMBRE  = ""
	SERVIDOR_NOMBRE = "Servidor"

	ERROR_PREFIJO           = "..."
	ERROR_NOMBRE            = ERROR_PREFIJO + "NOMBRE NO DISPONIBLE\n"
	ERROR_ENTRAR_NO_EXISTE  = ERROR_PREFIJO + "NO EXISTE ESA SALA\n"
	ERROR_ENTRAR_INVITACION = ERROR_PREFIJO + "NO ESTAS INVITADO A LA SALA\n"
	ERROR_DESCONOCIDO       = ERROR_PREFIJO + "MENSAJE INVÁLIDO\n"
	ERROR_HISTORIAL         = ERROR_PREFIJO + "Solicitaste el historial de una sala a la que no perteneces o no especificaste nombre\n"
  ERROR_INVITACION        = ERROR_PREFIJO + "NO TIENES PERMISO PARA INVITAR A ESA SALA\n"
	ERROR_SALA              = ERROR_PREFIJO + "NO PERTENECES A LA SALA %v\n"

	MENSAJE_ENVIADO = "...MENSAJE ENVIADO\n"

	EVENTO_PREFIJO             = "%v - "
	EVENTO_ENTRA_SALA          = EVENTO_PREFIJO + "\"%s\" SE UNIÓ A LA SALA\n"
	EVENTO_DEJA_SALA           = EVENTO_PREFIJO + "\"%s\" salió de la sala %v\n"
	EVENTO_SALA_NOMBRE         = EVENTO_PREFIJO + "\"%s\" CAMBIÓ SU NOMBRE A \"%s\"\n"
	EVENTO_PERSONAL_CREAR      = EVENTO_PREFIJO + "CREASTE LA SALA \"%s\"\n"
	EVENTO_PERSONAL_NOMBRE     = EVENTO_PREFIJO + "CAMBIASTE TU NOMBRE A \"%s\"\n"
	EVENTO_PERSONAL_ESTADO     = EVENTO_PREFIJO + "CAMBIASTE TU ESTADO A \"%s\"\n"

	MSJ_DESCONECTA = "\nDesconectado del servidor.\n"
)
